### ISSUE TITLE
Raw file multi-threaded access from Python?

### ISSUE THREAD

**Issue by keesh0** [ethz-institute-of-microbiology/fisher_py#18]
Hello,
Given the following C# multi-threaded interfaces.
Is multi-threaded access via fisher_py available?

from "UsingRawFileReader.pdf"
**Multi-threaded code**
As noted in the section above, the IRawDataPlus interface is an instance object, and should be used by only one thread.
However, the raw file reader can generate any number of such objects, so that any number of threads can access the
same raw file in parallel.
For multi-threaded code, the pattern is:
A manager object is created (from a file name), which cannot itself read any raw data.
This manager is then used to create IRawDataPlus interfaces for each thread, as detailed below:
The C# raw file reader includes an implementation of IRawFileThreadManager
The factory method RawFileReaderFactory.CreateThreadManager can be used to open a raw file, for use
by multiple threads.
For example:
var myThreadManager = RawFileReaderFactory.CreateThreadManager (path);
This can be used for multi-thread access to the same raw file.
All business logic still accesses the information using the IRawDataPlus interface. Application teams do not have to write
any thread synchronization or locking code.
The usage pattern is as follows.
Open a file returning a thread data manager:
Try
{
  myThreadManager = RawFileReaderFactory.CreateThreadManager (filename)
}
Catch exceptions
Exceptions may occur if the required raw file reader dll is not found, or a null string is sent for the raw file name.
The action of opening a file executes a small number of “one time” single threaded actions, such as:
• Opening the file on disk.
• Reading the file header (time stamps, operator name etc.)
• Reading sample information.
• Obtaining the list of detectors.
Important: This “thread manager” cannot itself read any raw data.
Assuming no exceptions, for each thread which needs access to data (including the current thread, if needed):
IRawDataPlus myThreadDataReader = myThreadManager. CreateThreadAccessor();
To test for errors, create a thread accessor.
This property:
/// <summary>
/// Gets the file error state.
/// </summary>
IFileError FileError { get; }
Can then be used to check for any errors (such as invalid file name).
Performance Note: Within the C# reader, there is no significant performance overhead in
“CreateThreadAccessor”. In evaluation of this, we have tested that in can be used within a “Parallel.For” pattern,
to make an accessor for each scan in a raw file.
Note: The method “CreateThreadAccessor();” is actually a member of the interface
“IRawFileThreadAccessor” which has other implementations noted later.
After all created threads have exited, call:
myThreadManager.Dispose();
Using this pattern all business logic for multi-threaded code is exactly the same as for single threaded code.
All interface members of IRawDataPlus can be used, with no concerns for locking or thread safety. Do not add any
additional locks in calling code.
Data for each thread is read in parallel (lockless), wherever possible. Some larger objects in the raw file use (thread safe)
lazy loading, such that, for example: The first thread which opens the MS data will incur a small overhead for opening
the MS data stream, then all other threads will share parallel access to that same stream.
Note: Locking may occur when a file is opened in real time mode (during data acquisition), as a real time data is
continually changing state. This locking is internal to the file reader, and calling code need not take any special action for
real time files.

**Alternate approaches to threading**
Even though the C# reader natively supports parallel access to data, not all file readers may support this, but “There’s an
interface for that”.
The interface “IRawFileThreadManager”
Is defined as follows:
public interface : IRawFileThreadAccessor, IDisposable
That is: When you open a raw file, and obtain this interface, as described above, you “dispose” to close the file.
The mechanism for allocating data to threads is descried in “IRawFileThreadAccessor”, so if the application layer
code opens a file, it may pass “IRawFileThreadAccessor” to the next layer of code.
As above, that code can call “CreateThreadAccessor”:
MyMethod(IRawFileThreadAccessor myThreadDataReader)
IRawDataPlus myThreadDataReader = myThreadDataReader. CreateThreadAccessor();
An advantage of this scheme is that an application can be designed to use other readers which do not support the
thread manager interface, by using another implementation of “IRawFileThreadAccessor”.
CommonCore already includes an implementation of this:
public class ThreadSafeRawFileAccess : IRawCache, IRawFileThreadAccessor
This class permits multi thread support (by IRawFileThreadAccessor) to be generated from any instance of
IRawDataPlus
Using this public constructor:
public ThreadSafeRawFileAccess(IRawDataPlus file).
Via this pattern, library code need not be aware of how the thread management is done. If the library code
(business logic) receives “IRawFileThreadAccessor” it will be able support multi-threaded access to any raw
file, from any file reader.
The difference is one of performance.
When using the C# raw file reader’s direct implementation (ThreadedFileFactory) the business logic will have
lockless parallel access to data. When the interface passed in is created by the class
“ThreadSafeRawFileAccess” then calls into the file are serialized via locks.
Note: In all cases
• The business logic need no add any additional locking.
• The business logic need not reference any specific file reading DLL.
• All required interfaces are contained in ThermoFisher.CommonCore.Data.dll

**Comment by dowerner** [comment]
Hello @keesh0 
I am not sure if I understand you correctly. Does your question relate to whether the existing raw file access can be used in multiple threads or do you ask for a specific class that is explicitly meant for this purpose? As I understand it, the .NET objects should have no issues with multi-threaded access, I even tested this and it ran without issue.

However, I am not sure if you are aware of the big limitations Python has when using multithreading: the biggest one being that python can only utilize one CPU core. This is why I would suggest you to use **multiprocessing** because there, multiple python processes are run that can then utilize multiple cores. A simple example:

```python
from fisher_py import RawFile
from fisher_py.data.business import TraceType
from multiprocessing import Pool

def do_stuff(num):
    print(f'starting process: {num}')
    filename = 'my_file.raw'
    
    raw_file = RawFile(filename)

    target_mass = 848.36862
    mass_tolerance_ppm = 10
    rt, i = raw_file.get_chromatogram(target_mass, mass_tolerance_ppm, TraceType.MassRange)
    mz, i2, charges, real_rt = raw_file.get_scan_ms1(1)

    target_mass = 848.36862
    mass_tolerance_ppm = 10
    rt, i = raw_file.get_chromatogram(target_mass, mass_tolerance_ppm, TraceType.MassRange)
    mz, i2, charges, real_rt = raw_file.get_scan_ms1(1)

    print(mz)

    print('------------------ PROCESS DONE -----------------------')

if __name__ == '__main__':

    with Pool(5) as p:
        p.map(do_stuff, [1, 2, 3, 4, 5])
```

There are some limitations as well with multiprocessing: one for instance being that the method that you want to run through the process pool workers, needs to be pickled.  https://docs.python.org/3/library/multiprocessing.html

I hope this helps you, feel free to reach out if you have more questions.

Cheers Dominik

**Comment by keesh0** [comment]
Thanks, I am using a pool from multiprocessing to speed up a small, but slow function.
But, I was unsure if the following raw_file 'handle' could safely be used independently in each task (passed into do_stuff)?
      raw_file = RawFileReaderAdapter.file_factory(inputRawFileName)

**Comment by dowerner** [comment]
This is no problem. In fact, the ```RawFile``` class uses the very same code snippet in its constructor, it is basically just a wrapper for the more complex object you get when you call ```file_factory```.
Since it is read only I also don't see any issues like race conditions. For sure I would always keep a backup of the data since I cannot guarantee that there are no issues in the DLLs shipped with the packages.

I will close the issue here, but feel free to open a new one if you encounter any problems,

Cheers Dominik

**Comment by keesh0** [comment]
Yes, raw_file: RawFileAccess cannot seem to be pickled.
So I simply pass the raw file name to each process (task) and then read it from within there.
This works fine on Windows, but on Mono (Linux), there are bad crashes.

`  
def MPTask(scan_num, step_scan_number, inputRawFileName):
    mzs = np.array([], dtype=np.float64)
    intensities = np.array([], dtype=np.float64)
    raw_file = RawFileReaderAdapter.file_factory(inputRawFileName)
    raw_file.select_instrument(Device.MS, 1)
    msLevel = GetMSLevel(raw_file, scan_num)
    if msLevel == 1:
        success, mzs, intensities = GetRawData(raw_file, scan_num)
        if success and mzs.size >= 1 and intensities.size >= 1:
            print(f'charge: {mzs[0]}, intensity: {intensities[0]}')
    raw_file.dispose()


task_items = [(scan_num, step_scan_number, inputRawFileName)
    for scan_num in range(first_scan_number, last_scan_number + 1, step_scan_number)]
pool.starmap(MPTask, task_items, chunksize=MP_CHUNK_SIZE)
`

`
* Assertion at mono-threads.c:500, condition `result' not met ================================================================= Native Crash Reporting ================================================================= Got a SIGABRT while executing native code. This usually indicates a fatal error in the mono runtime or one of the native libraries used by your application. ================================================================= ================================================================= Native stacktrace: ================================================================= 0x7facec3ae54c - /apps/software/biotools/mono/[6.12.0.182/lib/libmonosgen-2.0.so.1](http://6.12.0.182/lib/libmonosgen-2.0.so.1) : 0x7facec3ae899 - /apps/software/biotools/mono/[6.12.0.182/lib/libmonosgen-2.0.so.1](http://6.12.0.182/lib/libmonosgen-2.0.so.1) : 0x7facec33c0ff - /apps/software/biotools/mono/[6.12.0.182/lib/libmonosgen-2.0.so.1](http://6.12.0.182/lib/libmonosgen-2.0.so.1) : 0x7facec3adb8d - /apps/software/biotools/mono/[6.12.0.182/lib/libmonosgen-2.0.so.1](http://6.12.0.182/lib/libmonosgen-2.0.so.1) : 0x7facf25a2630 - /lib64/libpthread.so.0 : 0x7facf1af2387 - /lib64/libc.so.6 : gsignal 0x7facf1af3a78 - /lib64/libc.so.6 : abort 0x7facec57d8b4 - /apps/software/biotools/mono/[6.12.0.182/lib/libmonosgen-2.0.so.1](http://6.12.0.182/lib/libmonosgen-2.0.so.1) : 0x7facec5643e9 - /apps/software/biotools/mono/[6.12.0.182/lib/libmonosgen-2.0.so.1](http://6.12.0.182/lib/libmonosgen-2.0.so.1) : 0x7facec57d7de - /apps/software/biotools/mono/[6.12.0.182/lib/libmonosgen-2.0.so.1](http://6.12.0.182/lib/libmonosgen-2.0.so.1) : 0x7facec57dd70 - /apps/software/biotools/mono/[6.12.0.182/lib/libmonosgen-2.0.so.1](http://6.12.0.182/lib/libmonosgen-2.0.so.1) : monoeg_assertion_message 0x7facec57ddaa - /apps/software/biotools/mono/[6.12.0.182/lib/libmonosgen-2.0.so.1](http://6.12.0.182/lib/libmonosgen-2.0.so.1) : 0x7facec5733f0 - /apps/software/biotools/mono/[6.12.0.182/lib/libmonosgen-2.0.so.1](http://6.12.0.182/lib/libmonosgen-2.0.so.1) : mono_thread_info_attach 0x7facec4cac7f - /apps/software/biotools/mono/[6.12.0.182/lib/libmonosgen-2.0.so.1](http://6.12.0.182/lib/libmonosgen-2.0.so.1) : 0x7facf259aea5 - /lib64/libpthread.so.0 : 0x7facf1bbab0d - /lib64/libc.so.6 : clone
`

**Comment by dowerner** [comment]
I see. I am afraid there isn't much I can do on my side to fix multiprocessing for mono. One thing you could try if you haven't already, is to update Pythonnet. If the CLR from .NET Core is used instead of Mono it might work. Another option would be to port your analysis to C# or at least generate some intermediate result that you then can import in Python to process with Numpy, Scipy, etc. There are also Nuget packages for C# that let you use some scientific Python packages in C#.

**Comment by keesh0** [comment]
Thermo's  C# multithreading interface worked fine.
Thermo seems to encapsulate the threading details well.
Can you please expose the following to Python so that we could give it a try?

```
// expose CreateThreadManager() in Python
// expose CreateThreadAccessor() in Python
// expose FileError in Python
```
```
// --------------------------------------------------------------------------
// MT interface
var myThreadManager = RawFileReaderFactory.CreateThreadManager(filename);
IRawDataPlus rawFileMT = myThreadManager.CreateThreadAccessor();
IFileError fileErrorMT = rawFileMT.FileError;
...
Console.WriteLine("Using Max Degree Of Parallelism {0}", num_processors);
        int stepScanNumber = (int)(totalNumScans / num_processors);
        Parallel.ForEach(SteppedIntegerList(firstScanNumber, lastScanNumber+1, stepScanNumber), options, scan_num =>
        {
            IRawDataPlus rawFileMT = myThreadManager.CreateThreadAccessor();
            IFileError fileErrorMT = rawFileMT.FileError;
            if (fileErrorMT.HasError || fileErrorMT.HasWarning)
            {
                Console.WriteLine("Unable to access the RAW file using the IRawDataPlus class! {0}, {1}",
                    fileErrorMT.ErrorMessage, fileErrorMT.WarningMessage);
                return;
            }
            MPTask(rawFileMT, scan_num, stepScanNumber);
        });

    static void MPTask(IRawDataPlus rawFile, int scan_num, int step_scan_num)
        {
            Console.WriteLine("In thread starting scan: {0}", scan_num);
            rawFile.SelectInstrument(Device.MS, 1);
            var msLevel = GetMSLevel(rawFile, scan_num);
            if (msLevel == 1)
            {
                Boolean success;
                double[] mzs = new double[0];
                double[] intensities = new double[0];
                (success, mzs, intensities) = GetRawData(rawFile, scan_num);
                if (success && mzs.Length >= 1 && intensities.Length >= 1)
                {
                    Console.WriteLine("scan_num: {0} charge = {1}, intensity = {2}", scan_num, mzs[0], intensities[0]);
                }
            }
            rawFile.Dispose();
        }
// --------------------------------------------------------------------------
```

**Comment by dowerner** [comment]
I have added the wrappers for the classes you mentioned. Have a look at this PR #19 and let me know if this works for you.
