### ISSUE TITLE
[Help wanted] get_retention_time_from_scan_number throws TypeError

### ISSUE THREAD

**Issue by polichan** [ethz-institute-of-microbiology/fisher_py#21]
I tried to getting the retention time with scan number. I called  the ``get_retention_time_from_scan_number`` function like below, but it throws an exception which is ``TypeError: unsupported operand type(s) for -: 'list' and 'int'``. How can i fix the issue? Any help will be appreciate.

```python
ms2_scan_numbers = np.array(raw_file_source._ms2_filter_scan_numbers)
for scan_number in ms2_scan_numbers:
    ms2_scan_number = int(scan_number)
    ms2_rt = raw_file_source.get_retention_time_from_scan_number(ms2_scan_number)
```

**Comment by polichan** [comment]
I took a look at the function implementation. It seems that ``scan_number`` passed in is type of Int. ``self._scan_numbers `` is type of nd arrray. Could it be possibe to operate nd array with int? 

Detailed exception logs:

```
Traceback (most recent call last):
  File "E:\Projects\xcalibur\main.py", line 290, in <module>
    main()
  File "E:\Projects\xcalibur\main.py", line 279, in main
    gen_ms2()
  File "E:\Projects\xcalibur\main.py", line 212, in gen_ms2
    ms2_rt = raw_file_source.get_retention_time_from_scan_number(1)
  File "E:\Projects\xcalibur\venv\lib\site-packages\fisher_py\raw_file.py", line 294, in get_retention_time_from_scan_number
    idx = np.argmin(np.abs(self._scan_numbers - scan_number))
TypeError: unsupported operand type(s) for -: 'list' and 'int'
```

**Comment by dowerner** [comment]
Hi @polichan 
Thank you for reporting this. There was actually a bug since the "_scan_numbers" member was not converted to a numpy array. If you update the package, this issue should be resolved.

Feel free to create another issue should you encounter any problems.

**Comment by polichan** [comment]
> Hi @polichan Thank you for reporting this. There was actually a bug since the "_scan_numbers" member was not converted to a numpy array. If you update the package, this issue should be resolved.
> 
> Feel free to create another issue should you encounter any problems.

Pretty much thanks for your rapid reply on this issue. I updated the package and this issue is resolved.
