### ISSUE TITLE
Issues with instrument methods when using Mono

### ISSUE THREAD

**Issue by abdelq** [ethz-institute-of-microbiology/fisher_py#3]
I tried newer DLLs (`OpenMcdf`, `ThermoFisher.CommonCore.Data`, `ThermoFisher.CommonCore.RawFileReader`) in https://github.com/compomics/ThermoRawFileParser/releases/tag/v1.3.4 and the issue has been fixed. However, looks like the `.pdb`s are missing...

**Comment by dowerner** [comment]
Hello abdelq,
Sorry for replying so late to your issue. I am managing this project on behalf of the Institute of Microbiology but forgot to setup notifications for my own account. It is only now that I saw your issue report.
Can you describe to me in detail how to reproduce the issue? The main platform used during development of this package was was Windows 10. I only used Ubuntu to test some features. It is in my and the Institutes interest to make the use of this package as easy as possible.

**Comment by dowerner** [comment]
Due to inactivity I am closing this issue. Feel free to open a new one if anything new comes up.
