### ISSUE TITLE
Disable native thermo peak picking

### ISSUE THREAD

**Issue by TjobberTjob** [ethz-institute-of-microbiology/fisher_py#4]
Is there a way to disable the native Thermo peak picking using fisher-py? I know very little of the way this peak picking is implemented natively into the raw files, but looking at the ThermoRawFileParser (https://github.com/compomics/ThermoRawFileParser) an option -p is possible to disable this peak picking, returning, on average, 10+ times more peaks per spectra.

I would love if there was a way to achieve this using fisher-py, but from looking through the RawFile class and the documentation I can find no such option, is this manageable or completely not feasible with the current fisher-py?
![image](https://user-images.githubusercontent.com/31824117/151641997-63c37a76-d44f-4559-9f93-b4cfc35cff66.png)

**Comment by dowerner** [comment]
Hello TjobberTjob,
Sorry for replying so late to your issue. I am managing this project on behalf of the Institute of Microbiology but forgot to setup notifications for my own account. It is only now that I saw your issue report.
The thing with the RawFile class is that it is only a wrapper for the RawFileAccess class that provides the full set of features of the underlying ThermoFisher library. If you look at the example [here](https://github.com/ethz-institute-of-microbiology/fisher_py/blob/main/examples/raw_file_reader_example.py) you should see much more possibilites for interacting with scan data.

**Comment by dowerner** [comment]
Hello again,
I have added an [example](https://github.com/ethz-institute-of-microbiology/fisher_py/blob/main/examples/generate_mgf_file_example.py) based on the repository you have provided. Let me know if it suits your needs. In any case, if you know C# well it should be quite straight forward to port code from C# based projects like ThermoRawFileParser to work in Python.
